name: commonforms-in-browser
region: fra

static_sites:
  - name: web
    github:
      repo: SimplePDF/commonforms-in-browser
      branch: master
      deploy_on_push: true

    build_command: npm run build
    output_dir: dist

    environment_slug: node-js

    envs:
      - key: NODE_VERSION
        value: "22"

    routes:
      - path: /

    catchall_document: index.html
